In [9]:
%load_ext autoreload
%autoreload 2
%config InlineBackend.figure_format = 'svg'
from src.general.io_handling import pickle_in_data
import numpy as np
np.set_printoptions(suppress=True)

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [15]:
path = "/nfs/arupclab001/Optimal_Protocol_bnAbs_arupc_lab001/data/raw/Trials_dr_0.02_muij_0.05_bins_15/phylogenetic_trees/"

sequences_prime = pickle_in_data(path + "Sigma_1.2/trajectory_3")

In [16]:
sequences_boost = pickle_in_data(path + "Sigma_1.2/injection_2_sig_0.19/trajectory_3")

In [17]:
sequences_prime.shape

(245, 1500, 17)

In [18]:
sequences_boost.shape

(252, 1500, 17)

In [41]:
np.sum(np.sum(sequences_boost[245],axis=0)[2:])

50.0

In [46]:
np.sum(sequences_boost[-1], axis=0)

array([174289.,    443.,      4.,      2.,      1.,      3.,      0.,
            0.,     13.,    141.,      6.,      4.,      4.,      6.,
            5.,      5.,      6.])

In [20]:
np.sum(sequences_prime[-1],axis=0)

array([90975.,   281.,    24.,    15.,     8.,     7.,     0.,     0.,
           0.,    21.,     8.,    16.,    18.,    24.,    21.,    14.,
          24.])

In [13]:
np.sum(sequences[-1], axis=0)

array([174289.,    443.,      4.,      2.,      1.,      3.,      0.,
            0.,     13.,    141.,      6.,      4.,      4.,      6.,
            5.,      5.,      6.])